# TracerX Marker Selection Pipeline - Multi-Patient Template
# This template is used by multi_patient.sh to generate patient-specific configs
# Placeholders will be replaced automatically during multi-patient processing

# Patient and analysis identification (will be replaced with actual patient ID)
patient_id: "PLACEHOLDER_PATIENT_ID"

# Input files and directories (placeholders will be replaced automatically)
input:
  ssm_file: "PLACEHOLDER_SSM_FILE"      # Path to patient's SSM file  
  code_dir: "PLACEHOLDER_CODE_DIR"      # TracerX-MP repository directory

# Output configuration (patient directory will be created automatically)
output:
  base_dir: "PLACEHOLDER_OUTPUT_DIR"    # Patient-specific output directory

# Step 1: Bootstrap configuration
bootstrap:
  num_bootstraps: 100  # Standard number of bootstrap samples for production

# Step 2: PhyloWGS configuration  
phylowgs:
  num_chains: 5        # Number of MCMC chains to run
  parallel_limit: 10   # Conservative limit for multi-patient workloads (vs 50 for single)

# Step 4: Marker selection configuration
marker_selection:
  read_depth: 1500

# HPC/SLURM configuration - Conservative settings for multi-patient workload
hpc:
  # Step-specific resource allocation (reduced from single-patient for cluster efficiency)
  bootstrap:
    partition: "pool1"
    cpus_per_task: 2        # Conservative CPU allocation
    memory: "8G"            # Reduced from 16G for multi-patient efficiency
    walltime: "02:00:00"    # Standard walltime
  
  phylowgs:
    partition: "pool1" 
    cpus_per_task: 5        # Standard CPU allocation
    memory: "8G"            # Standard memory allocation
    walltime: "04:00:00"    # Reduced from 12h for faster multi-patient throughput
  
  aggregation:
    partition: "pool1"
    cpus_per_task: 1  
    memory: "16G"           # Higher memory for aggregation
    walltime: "02:00:00"    # Reduced from 4h for multi-patient efficiency
  
  marker_selection:
    partition: "pool1"
    cpus_per_task: 1
    memory: "16G"           # Higher memory for optimization
    walltime: "02:00:00"    # Reduced from 6h for multi-patient efficiency
    modules: ["gurobi1102"]  # Required modules to load