# Patient and analysis identification
patient_id: "ppi_115"

# Input files and directories - UPDATE THESE PATHS FOR YOUR ENVIRONMENT
input:
  ssm_file: "/home/ssabata/mase-phi-hpc/data/vaf_filter_test/ssm_ppi_115.txt"
  code_dir: "/home/ssabata/mase-phi-hpc/"  

# Output configuration
output:
  base_dir: "/home/ssabata/patient_data/vaf_filter_test/"  # Patient base directory

# Step 1: Bootstrap configuration
bootstrap:
  num_bootstraps: 10  # Number of bootstrap samples to generate

# Step 2: PhyloWGS configuration  
phylowgs:
  num_chains: 5      # Number of chains used for PhyloWGS 
  parallel_limit: 50  # Maximum number of parallel jobs in SLURM array

# Step 4: Marker selection configuration
marker_selection:
  read_depth: 1500

# HPC/SLURM configuration
hpc:
  # Step-specific resource allocation
  bootstrap:
    partition: "pool1"
    cpus_per_task: 1
    memory: "16G"
    walltime: "02:00:00"
  
  phylowgs:
    partition: "pool1" 
    cpus_per_task: 5
    memory: "8G"
    walltime: "12:00:00"
  
  aggregation:
    partition: "pool1"
    cpus_per_task: 1  
    memory: "16G"
    walltime: "04:00:00"
  
  marker_selection:
    partition: "pool1"
    cpus_per_task: 1
    memory: "16G" 
    walltime: "06:00:00"
    modules: ["gurobi1102"]  # make sure to load your version of gurobi here

